name: notes_mspacman-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pip:
    - scipy
    - matplotlib
    - pyfftw
    - "ipython[all]"
    - "git+https://github.com/davidlu89/pytf.git"
    - "git+https://github.com/davidlu89/mspacman.git"
